name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller
        pip install mido python-rtmidi

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole midi_chord_generator.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: midi_chord_generator_exe
        path: dist/midi_chord_generator.exe
